// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC18HiVXtoMMYi9ehJDyv0hMxRV5FmAOy0',
    appId: '1:824214002874:web:bd42aa8313580d87c23683',
    messagingSenderId: '824214002874',
    projectId: 'carta-de-vinhos-320c1',
    authDomain: 'carta-de-vinhos-320c1.firebaseapp.com',
    storageBucket: 'carta-de-vinhos-320c1.firebasestorage.app',
    measurementId: 'G-N0RRC8R1B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOf9tAbkQoBdzH93IwGohsslyWeylfRjU',
    appId: '1:824214002874:android:0a1957089317a978c23683',
    messagingSenderId: '824214002874',
    projectId: 'carta-de-vinhos-320c1',
    authDomain: 'carta-de-vinhos-320c1.firebaseapp.com',
    storageBucket: 'carta-de-vinhos-320c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC18HiVXtoMMYi9ehJDyv0hMxRV5FmAOy0',
    appId: '1:824214002874:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '824214002874',
    projectId: 'carta-de-vinhos-320c1',
    authDomain: 'carta-de-vinhos-320c1.firebaseapp.com',
    storageBucket: 'carta-de-vinhos-320c1.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.example.appVinhoTaverna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC18HiVXtoMMYi9ehJDyv0hMxRV5FmAOy0',
    appId: '1:824214002874:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '824214002874',
    projectId: 'carta-de-vinhos-320c1',
    authDomain: 'carta-de-vinhos-320c1.firebaseapp.com',
    storageBucket: 'carta-de-vinhos-320c1.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.example.appVinhoTaverna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC18HiVXtoMMYi9ehJDyv0hMxRV5FmAOy0',
    appId: '1:824214002874:web:bd42aa8313580d87c23683',
    messagingSenderId: '824214002874',
    projectId: 'carta-de-vinhos-320c1',
    authDomain: 'carta-de-vinhos-320c1.firebaseapp.com',
    storageBucket: 'carta-de-vinhos-320c1.firebasestorage.app',
  );
}
