// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8P2F6w3xO3LOTdOXmzxklWEuTocbdma0',
    appId: '1:886089057823:web:0a52c33ef73b249568372a',
    messagingSenderId: '886089057823',
    projectId: 'carta-vinhos-fd287',
    authDomain: 'carta-vinhos-fd287.firebaseapp.com',
    storageBucket: 'carta-vinhos-fd287.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8P2F6w3xO3LOTdOXmzxklWEuTocbdma0',
    appId: '1:886089057823:android:ANDROID_APP_ID',
    messagingSenderId: '886089057823',
    projectId: 'carta-vinhos-fd287',
    authDomain: 'carta-vinhos-fd287.firebaseapp.com',
    storageBucket: 'carta-vinhos-fd287.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8P2F6w3xO3LOTdOXmzxklWEuTocbdma0',
    appId: '1:886089057823:ios:IOS_APP_ID',
    messagingSenderId: '886089057823',
    projectId: 'carta-vinhos-fd287',
    authDomain: 'carta-vinhos-fd287.firebaseapp.com',
    storageBucket: 'carta-vinhos-fd287.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.example.appVinhoTaverna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8P2F6w3xO3LOTdOXmzxklWEuTocbdma0',
    appId: '1:886089057823:ios:IOS_APP_ID',
    messagingSenderId: '886089057823',
    projectId: 'carta-vinhos-fd287',
    authDomain: 'carta-vinhos-fd287.firebaseapp.com',
    storageBucket: 'carta-vinhos-fd287.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.example.appVinhoTaverna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8P2F6w3xO3LOTdOXmzxklWEuTocbdma0',
    appId: '1:886089057823:web:0a52c33ef73b249568372a',
    messagingSenderId: '886089057823',
    projectId: 'carta-vinhos-fd287',
    authDomain: 'carta-vinhos-fd287.firebaseapp.com',
    storageBucket: 'carta-vinhos-fd287.firebasestorage.app',
  );
}
