// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf8bG_rH7pP8h4XPxuPAtZO1jhPNR7u2Q',
    appId: '1:439489726638:web:8d22eee21da0b23650c53f',
    messagingSenderId: '439489726638',
    projectId: 'taverna-vinhos-eu-gm',
    authDomain: 'taverna-vinhos-eu-gm.firebaseapp.com',
    storageBucket: 'taverna-vinhos-eu-gm.firebasestorage.app',
    measurementId: 'G-J7JLY4SXWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHt_ZGMCQ3xRuN-GvcWRaPZKgSpnRsIHI',
    appId: '1:439489726638:android:9e85c3989de213e150c53f',
    messagingSenderId: '439489726638',
    projectId: 'taverna-vinhos-eu-gm',
    storageBucket: 'taverna-vinhos-eu-gm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLDkVcmzpzV1JkyBMb1OnP2I7JeH1__tg',
    appId: '1:439489726638:ios:e5cdc31055f5ad7750c53f',
    messagingSenderId: '439489726638',
    projectId: 'taverna-vinhos-eu-gm',
    storageBucket: 'taverna-vinhos-eu-gm.firebasestorage.app',
    iosBundleId: 'com.example.appVinhoTaverna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLDkVcmzpzV1JkyBMb1OnP2I7JeH1__tg',
    appId: '1:439489726638:ios:e5cdc31055f5ad7750c53f',
    messagingSenderId: '439489726638',
    projectId: 'taverna-vinhos-eu-gm',
    storageBucket: 'taverna-vinhos-eu-gm.firebasestorage.app',
    iosBundleId: 'com.example.appVinhoTaverna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf8bG_rH7pP8h4XPxuPAtZO1jhPNR7u2Q',
    appId: '1:439489726638:web:add793d62560c70a50c53f',
    messagingSenderId: '439489726638',
    projectId: 'taverna-vinhos-eu-gm',
    authDomain: 'taverna-vinhos-eu-gm.firebaseapp.com',
    storageBucket: 'taverna-vinhos-eu-gm.firebasestorage.app',
    measurementId: 'G-54X2B1TD0Y',
  );

}